[target.thumbv7m-none-eabi]
# runner = 'probe-rs run --chip STM32F103CB --probe 0d28:0204'
runner = 'probe-rs run --chip STM32F103CB --probe 0483:3748'


rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x"
]

[build]
target = "thumbv7m-none-eabi"